### ISSUE TITLE
[Roadmap]: Update Demo & Docs

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/lczerolens#10]
## Description

With the new API changes, the demo and the documentation need to be updated.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class test are written
* [ ] The code was reviewed

## Tasks

* [x] #20
* [x] #21
* [x] #22
* [x] #19
