### ISSUE TITLE
Rewrite dataset analysis with generator

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/lczerolens#13]
## Description

More memory friendly.

## Acceptance Criterion

* [x] The code is documented
* [x] Utilities and class test are written
* [x] The code was reviewed

## Tasks

* [x] Change the code to make dataset lense iterators
