### ISSUE TITLE
Rewrite using NNSight

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/lczerolens#24]
## Description

Rewrite the wrapper using the base class from NNsight.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class test are written

## Tasks

* [x] Make the wrapper inherit from NNsight
* [x] Convert the wrapper methods
* [ ] Convert the lenses
