### ISSUE TITLE
Abstract functions to classes

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/lczerolens#25]
## Description

Refactor the functions into classes

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class tests are written

## Tasks

* [ ] Create a `LczeroBoard` class
* [x] Improve the `Game` class
