### ISSUE TITLE
Better compatibility with Colab

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/lczerolens#27]
## Description

Better compatibility with Colab in order to have faster installs

## Acceptance Criterion

* [ ] The code was testes

## Tasks

* [ ] Find minimal dependencies needed to work on Colab
* [ ] Create an install extras for Colab
