### ISSUE TITLE
Integrate with Game and Puzzle datasets

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/lczerolens#31]
## Description

Integrate with Game and Puzzle datasets.

## Acceptance Criterion

* [x] The code is documented
* [x] Utilities and class test are written
* [x] The code was reviewed

## Tasks

* [x] Create the Game and Puzzle datasets
* [x] Create the Puzzle module
* [x] Make an illustrative script or a notebook
