### ISSUE TITLE
Rewrite LRP without `zennit`

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/lczerolens#38]
## Description

Rewrite LRP without needing `zennit` by re-writing layers with custom rules.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class tests are written
* [ ] The code was reviewed

## Tasks

* [ ] Rewrite the layers
* [ ] Write tests for the layers
* [ ] Define a mapping per rule
