### ISSUE TITLE
Batching label prediction

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/lczerolens#9]
## Description

Batch the label prediction.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class tests are written
* [ ] The code was reviewed

## Tasks

* [ ] Compute labels per batch option
* [ ] Make the concept dataset batch labelise
* [ ] Optionally make it on device if available
